title: Kruize Documentation
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://shekhar316.github.io/kruize-docs

defaults:
  - scope:
      path: "docs" 
      type: "pages"
    values:
      layout: "default"
      
aux_links:
  Template Repository: https://github.com/shekhar316/kruize-docs
