title: Kruize Documentation
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://shekhar316.github.io/kruize-docs

aux_links:
  Template Repository: https://github.com/shekhar316/kruize-docs
